# Generated by Django 2.2 on 2023-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230502_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
